### ISSUE TITLE
use updated 3P keys

### ISSUE THREAD

**Issue by ca333** [blur-network/dpow-blur#13]
https://github.com/blur-network/dpow-blur/blob/1bc62ea96921c1094c53803a764e0a10db023912/src/cryptonote_core/komodo_notaries.cpp#L65

plz update to https://github.com/KomodoPlatform/dPoW/blob/master/iguana/3rd_party

**Comment by who-biz** [comment]
@ca333 thanks for letting me know. 

Done in commit: https://github.com/blur-network/dpow-blur/commit/0cbb1cf09aa3fe6c0d298209c74d9dc98e366803

**Comment by who-biz** [comment]
Will leave this open until they're merged into default branch.

**Comment by who-biz** [comment]
@ca333 please note, these have been merged into default branch, as of commit https://github.com/blur-network/dpow-blur/commit/10adfad832fa97e9a66add5f6def6755991d78de. 

For the future, since we already have keys generated (for testnet), those keys have been moved over to the <a href="https://github.com/blur-network/dpow-blur/tree/testnet">`testnet`</a> branch. I will be making most development changes on that branch first, as a result.

Will also be adding some info to README, for disambiguation. This way, others may independently tool around with funded testnet wallets, if they choose to do so.

Closing as resolved.  Let me know if those changes aren't adequate, for any reason.
